### ISSUE TITLE
pipeline for timesteps

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#1]
Timesteps define the resolution of the GIF frames. They interact with other datasets but deserve their own champion because they're complex and essential.

- timesteps are determined by the availability of precip data (or they have been, anyway)
- timestep processor should create an .rds file (perhaps a data.frame containing columns for two formats, POSIXct and character string?)
- timestep .rds file should be referenced by everything downstream - aligning the storm track timesteps, displaying the date-time on the plot, and so on. Make sure this is the case.
- timezones will differ by vizzie (because storms occur in different timezones). Ensure that this information only gets entered/determined in one location (`parameters`?) and is consistent throughout the vizzie (e.g., shows up in these 6 files in Maria: https://github.com/USGS-VIZLAB/hurricane-maria/search?utf8=%E2%9C%93&q=America%2FPuerto_Rico&type=).

**Comment by aappling-usgs** [comment]
for data pulling, just use `start` and `end` in the configuration file.

in processing phase, we'll need to align the data to a single set of timesteps (resolution)

**Comment by aappling-usgs** [comment]
i will get this started and then will be happy to hand it off

**Comment by dblodgett-usgs** [comment]
I think I fixed this up here: https://github.com/USGS-VIZLAB/vizstorm-GIF/blob/master/2_process/src/choose_timesteps.R#L5 ? I only created posxct, but it is the time steps from the precip in UTC.

**Comment by aappling-usgs** [comment]
i think a vector of POSIXct elements taken from precip is exactly what we want :+1: - closing
