### ISSUE TITLE
Dynamic legend fails poorly when there is no longer a dot from the storm

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizstorm-GIF#101]
Sometimes we'll want the animation to extend past when NOAA has a storm track/dot for a hurricane. The legend currently throws an error when we hit a timestep where this is the case (see [oct 10](https://owi.usgs.gov/vizlab/hurricane-matthew/) for example. 

We already know we want to be able to support a gif w/o a hurricane, but what do we do when the hurricane/TS is only there for part of the animation?

**Comment by jread-usgs** [comment]
Not sure what should happen when this is the case:
 - show the color/category of the last dot that appeared?
 - remove this part of the legend for timesteps when the storm is no longer active?
 - change to a generic storm name (w/o category)?

**Comment by aappling-usgs** [comment]
Unless we have the storm name somewhere else on the GIF, I think it'd be nice to have some variant stay written in the legend. What if we used the storm track line as the symbol (line in place of dot) and switched to the generic storm name?

**Comment by jread-usgs** [comment]
I prefer that proposal ☝️ 
> used the storm track line as the symbol (line in place of dot) and switched to the generic storm name

**Comment by jread-usgs** [comment]
Fixed
