### ISSUE TITLE
Enable download of precip data from Windows

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#102]
Right now we can only do it on Mac.

**Comment by dblodgett-usgs** [comment]
Theoretically, using this version of `ncdf4` should do it: https://github.com/mdsumner/ncdf4 I think someone tried and it didn't work?

**Comment by lindsaycarr** [comment]
I have the most recent version of `ncdf4` downloaded from GitHub (`v1.16.9001`) and I get the following:

```
nc <- ncdf4::nc_open("https://cida.usgs.gov/thredds/dodsC/stageiv_combined")
Error in R_nc4_open: NetCDF: Invalid argument
Error in ncdf4::nc_open("https://cida.usgs.gov/thredds/dodsC/stageiv_combined") : 
  Error in nc_open trying to open file https://cida.usgs.gov/thredds/dodsC/stageiv_combined
```

**Comment by dblodgett-usgs** [comment]
From the `mdsumner` fork?

**Comment by aappling-usgs** [comment]
I have a docker container with ncdf4 on debian (based on rocker/geospatial:latest) and I get the following:
```r
> nc <- ncdf4::nc_open("https://cida.usgs.gov/thredds/dodsC/stageiv_combined")
>
```
:grin:

**Comment by lindsaycarr** [comment]
@dblodgett-usgs yes, from that fork

**Comment by dblodgett-usgs** [comment]
https://github.com/mdsumner/ncdf4/issues/1
