### ISSUE TITLE
add water bodies

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#119]
Showing water bodies would be useful for orientation in the August 2018 flooding near Madison, and for Lake Pontchartrain to cover up what looked like a flow line through the ocean

![image](https://user-images.githubusercontent.com/12039957/44545996-9b1e2b00-a6e4-11e8-9a4f-7575cd3ff6d7.png)

**Comment by dblodgett-usgs** [comment]
Work I recently did for https://github.com/dblodgett-usgs/nhdplusTools makes this real easy. 
See: https://github.com/dblodgett-usgs/nhdplusTools/blob/master/R/get_nhdplus.R#L53

You can pass that "nhdarea", and "nhdwaterbody" for the `layer` input. Area is the wide river cover polygons waterbody is lakes. `box` is just an sf polygon that satisfies the area you want. 

Here's where I use that function in an exported function. https://github.com/dblodgett-usgs/nhdplusTools/blob/e38f41fe79dfcf2ee7cf7020a4d943f7886b2b95/R/subset.R#L177
