### ISSUE TITLE
sparklines viz function

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#12]

**Comment by lindsaycarr** [comment]
Handling gaps in the data!

- interpolate small gaps. if the gap is small, linear is likely appropriate. if the gap is larger, interpolation would be a bad idea. Threshold for "small gap" is set in viz_config, but not sure we'd actually change across vizzies
- if the gage goes down for > threshold, we do an X and then don't show data.
- if a gage goes down and then comes back up, we do an X at the end of the first period, a blank spot while it's down, and then pick up with a new polygon when it comes back. Like so: 

![image](https://user-images.githubusercontent.com/13220910/42645569-ffef03ac-85c3-11e8-8789-8223af61bbf6.png)

To start, 5 hrs is going to be the threshold for small.
