### ISSUE TITLE
Precip data not working after change of projection.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/vizstorm-GIF#140]
This issue was discovered when changing projection and view box. It turned out that the NetCDF file being pulled from the Geo Data Portal was covering the incorrect area. the `stencil` being passed to `geoknife` was correct but for some reason, the GDP was pulling data for the wrong side of the country. 
e.g. We were getting this:  
<img width="498" alt="screen shot 2018-09-12 at 9 00 45 pm" src="https://user-images.githubusercontent.com/1492803/45484617-5b15fb00-b71a-11e8-9165-8721651cbf6c.png">  
When we wanted this:  
<img width="550" alt="screen shot 2018-09-13 at 5 57 14 am" src="https://user-images.githubusercontent.com/1492803/45484618-5cdfbe80-b71a-11e8-809b-4f05666fd2be.png">

The fix is to limit the size of the stencil being passed to the GDP to not overlap the edge of the source data.

**Comment by jread-usgs** [comment]
fixed
