### ISSUE TITLE
add more coastal plain gages

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#153]
depict more gages on the lower Cape Fear, lower Pee Dee and Waccamaw Rivers in the coastal plain of North and South Carolina

**Comment by jread-usgs** [comment]
This is harder to do than I thought it would be...hmm. 


| site_num   | name | NWS stage? |
|----------|:-------------:|------:|
| [02110550](https://waterdata.usgs.gov/usa/nwis/uv?02110550) |  WACCAMAW RIVER ABOVE CONWAY | *no* |
| [02110500](https://waterdata.usgs.gov/usa/nwis/uv?site_no=02110500) | WACCAMAW RIVER NEAR LONGS | *no* |

etc...
