### ISSUE TITLE
explore an outtro

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#154]
* replace sparklines with text about USGS activities & how to learn more
* display more/all USGS gage points
* add points for rapid deployment gages if possible (see #155 for the fetch step)

**Comment by jread-usgs** [comment]
We may want to use gifsicle to change the delay on these outro frames, since we'll be file size limited for twitter. E.g., if we want a single outro frame to play for 10s, we should consider creating a frame and set that delay, instead of duplicating frames.

**Comment by aappling-usgs** [comment]
work on tasks in this order:
- [ ] fetching and plotting RDGs
- [ ] add text: "see the rest of the story at https://waterdata.usgs.gov/nwis"
- [ ] work on gifsicle timing (see above)
- [ ] add all stationary gages if it's looking good

**Comment by jread-usgs** [comment]
Also wondering if we'll need to tweak the gage part of the legend during the outro. Seems likely, since "flooded" won't be relevant.

**Comment by aappling-usgs** [comment]
yeah. what if we borrowed laura's color scheme, adding non-focus gages in light blue?
![image](https://user-images.githubusercontent.com/12039957/45588086-079fda80-b8dd-11e8-8361-49366481fe46.png)
i'm picturing a completely different color for the RDGs, too - orange, something emergency-like?

and then we could possibly leave the selected gages as-are and then just add two lines of legend for the new site types
