### ISSUE TITLE
Need to fix fetch_precip_data()

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/vizstorm-GIF#237]
Updates with some projection things and `sp` documented [here](https://r-spatial.org/r/2020/03/17/wkt.html#crs-objects-in-sp), revealed an issue with setting the CRS using `___@proj4string <-`. So, the solution is to change `stencil@proj4string` to `sp::proj4string(stencil)` [here in fetch_precip_data()](https://github.com/USGS-VIZLAB/vizstorm-GIF/blob/master/1_fetch/src/fetch_precip_nc.R#L24).

![image](https://user-images.githubusercontent.com/13220910/119209303-7e68da80-ba6b-11eb-88ee-5a0df4a60f5f.png)

**Comment by ceenell** [comment]
This was resolved in https://github.com/USGS-VIZLAB/vizstorm-GIF/pull/241
