### ISSUE TITLE
Fixes during `Henri-2021` that need to get migrated to `main`

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/vizstorm-GIF#239]
Running list of everything we had to adjust that needs to make it into the `main` repo:

- [ ] Switch river geom fetch to using nhdplustools as the source (see https://github.com/USGS-VIZLAB/vizstorm-GIF/commit/4bd309a21050592e931473800d69e8dff9a86cb2#diff-1aa42baff6599120ec10682d10f92b046bacb4237e17359cba55397949618b0b)
- [ ] Implement the `sp` stencil bug issue mentioned in #237 (see https://github.com/USGS-VIZLAB/vizstorm-GIF/blob/Henri-2021/1_fetch/src/fetch_precip_nc.R#L24)
- [ ] Add the `remake_file = getOption()` solution since this pipeline was built before the switch to the `getters.yml` approach. Although, might be able to set the option for the whole pipeline instead of adding this in a bunch of places (see https://github.com/USGS-VIZLAB/vizstorm-GIF/commit/7ac3ed7c236cc7bddb492834abf0647bb2494073#diff-1965d7a54599d150f5f6e5609f4db440418fee35d77dcdb3e3e1460a4dcf18be)
- [ ] Strip out the `dim()` attribute before binding columns (see https://github.com/USGS-VIZLAB/vizstorm-GIF/commit/a007951bcfcf1bc815f1708986a640e08c93b4fe)
- [ ] Add timestep names back to the precip rasters (see https://github.com/USGS-VIZLAB/vizstorm-GIF/commit/1330bc67b1cfc61144dc8057f52f16430c17903e)
- [ ] Include the `par(mai = c(0,0,0,0))` for the precip plot function bc we discovered that the setting was somehow getting changed during Sally (see https://github.com/USGS-VIZLAB/vizstorm-GIF/commit/bbec9f1887da2865394761831cda8bdb90442209)
- [ ] Edit the mustache template for the outro gif tasks to use `timeline_fun_a` and not `datetime_fun_a`. We never made that switch there after we implemented the new time visual solution (see ???)
- [ ] Add note to `viz_config.yml` about how to look up `stn` code (see https://github.com/USGS-VIZLAB/vizstorm-GIF/blob/Sally-2020/viz_config.yml#L4)

Look at the final files in the `Henri-2021` branch that go with the commits above in case there were additional commits that improved those. Just included those to help orient you to the needed changes.

**Comment by jread-usgs** [comment]
wow, that's a lot of buggy-stuff. Nice work tracking it all down.

**Comment by lindsayplatt** [comment]
@collnell still rockin' it, despite this old, buggy repo 😭

**Comment by collnell** [comment]
- [ ] `gage_river_geometry` needs to be revisited, was not plotting correctly on `Henri-2021`

**Comment by lindsayplatt** [comment]
@collnell I think all of that except `gage_river_geometry` was fixed in #241?

**Comment by collnell** [comment]
Closing this issue. After working in Ida, I believe the challenges with `gage_river_geometry` for Henri could have been addressed by a force rebuild.
