### ISSUE TITLE
task table(s) for animation frames

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#27]
Let's use a scipiper task table or two to save image files for the animation frames generated by the functions described in #13 and #26. I think it may be simplest to have one task table for #13 and one for #26...but also be thinking about how these frames are going to get bundled up again into a single movie after they've been generated.

Rows=tasks of the task table should be timesteps. There could be one column=step, which would be to generate an animation frame, or there could be multiple columns=steps where each column is to generate an animation frame for the same timestep but with different resolution, aspect ratio, image format, etc -
 whatever is needed to allow us to produce all the different types of GIFs/movies we want to produce.

**Comment by jzwart** [comment]
Should this live in `2_process` or `6_visualize`? or make a new folder like `3_gif_tasks` or something?

**Comment by aappling-usgs** [comment]
`6_visualize`

**Comment by aappling-usgs** [comment]
We're rolling with the task table now.
