### ISSUE TITLE
combination phase to collect task table results into movie

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#28]
See #27 for how we're going to try generating animation frames. there will also need to be a function and remake recipe (this issue) that draws together the animation frames into one or several movies (all the same timesteps and visual contents for each movie, but there might be movies with different resolution, aspect ratio, file format, etc.)

We could possibly use this issue as the prompt to add a combination phase to scipiper (https://github.com/USGS-R/scipiper/issues/52#issuecomment-402779737), or we could have this combination function occur in the same higher-level remake file that was responsible for planning, creating, and looping through the task table[s].

If there are different movie formats, there may be several combination operations, and it's possible that each of these combination operations should be a task or step within yet another task table.

**Comment by jread-usgs** [comment]
Yes, this would be a nice opportunity to prototype what a "combine" would look like :+1:

**Comment by aappling-usgs** [comment]
Punting on the scipiper combine for the sake of getting to the vizstorm MVP, but I think we have a pretty reasonable system in place now.
