### ISSUE TITLE
usgs logo viz function

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#29]
function to add a semi-transparent usgs logo to the plot in a position dictated by the arguments to this function. this function will be called by #13.

**Comment by jread-usgs** [comment]
GIFs don't support semi transparency for pixels (it is all or none).

**Comment by aappling-usgs** [comment]
Rats. Well, light grey, then.
![image](https://user-images.githubusercontent.com/12039957/42513765-bd1bd9f0-8425-11e8-8b20-0ae4a5538836.png)

**Comment by jread-usgs** [comment]
Yes, we can, but if instead we are really explicit about colors (including limiting us to a 256 color palette), we'll make it easier to see what the true color (i.e., GIF export) will look like

**Comment by aappling-usgs** [comment]
looks like @jread-usgs has this under control in https://github.com/USGS-VIZLAB/vizstorm-GIF/pull/47.
