### ISSUE TITLE
pipeline for gage information

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#3]
Site point information - gage coordinates, flood stage thresholds, and any additional site data by which we plan to order the sparklines - may come from multiple source datasets, so data pulls from these various datasets may need to be coordinated.

At least in recent vizzies, the availability of NWS flood stage information has largely determined the list of sites for which NWIS site information & stage data were pulled.

We also want some way to be able to specify which sites we want to include in the final movie, probably after some initial broader data pull that gives us the info we need to be able to choose that final site list.

**Comment by lindsaycarr** [comment]
Common subsetting:
Exclude gages that don't have NWS flood stage.
Filter out gages not in viewbox.

Examples of custom filtering functions per storm:
Filter based on not being predicted to exceed flood stage.
Hand drawn polygon.
Filter out smaller gages (use drainage areas).
Hand picked (manual exclusion) - remove tidal gages, really messy looking ones, gages going offline

**Comment by lindsaycarr** [comment]
After #42, there are 245 sites:

![image](https://user-images.githubusercontent.com/13220910/42598055-993728cc-8520-11e8-8e5b-a67d13139316.png)

**Comment by aappling-usgs** [comment]
Nice, that's a lot of cleanup! might still be more gages than we'd want to show sparklines for, but gets us to a much more tractable number of possibilities

**Comment by lindsaycarr** [comment]
I think this can be closed now. I don't think it's within scope of this sprint to work on pruning the gage list any more in the custom function.
