### ISSUE TITLE
datetime viz function

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#30]
The date, and possibly also the time (might vary for hurricanes vs inland floods), needs to be displayed on the plot somewhere. This function should provide that plot.

Nice to have: One creative turn to consider might be to make this info graphical in some way - could be a calendar with date squares filling in over time, for example. Something to help people see where they are in time, and connect it to where they were in their own lives at each time point, without having to read and think about a text-based date-time stamp.

**Comment by jread-usgs** [comment]
> could be a calendar with date squares filling in over time, for example
cool idea

**Comment by jzwart** [comment]
closed via #76
