### ISSUE TITLE
display storm by storm type

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#72]
hurricane harvey was actually tropical storm harvey for a while. can we have the legend and the dot color change over time to show how the storm is changing type?

**Comment by aappling-usgs** [comment]
MVP: dot changes color, add a few lines to the legend for all the possible storm types

**Comment by jread-usgs** [comment]
Here is an example of how Harvey changed:
![image](https://user-images.githubusercontent.com/2349007/42701356-fb6c16ee-868b-11e8-9637-96bc8158aed2.png)

**Comment by dblodgett-usgs** [comment]
I'll start with the dot, but having the line be different colors should be doable as a simple add on.

**Comment by dblodgett-usgs** [comment]
```
> dput(unique(storm_line$STORMTYPE))
c("Low", "Tropical Depression", "Tropical Storm", "Tropical Wave", 
"Hurricane1", "Hurricane2", "Hurricane3", "Hurricane4", "Extratropical Cyclone")
```
`["#009900", "#ffff00", "#ff9933", "#ff0000", "#ff00ff"]`
4 ![screen shot 2018-07-13 at 12 52 58 pm](https://user-images.githubusercontent.com/1492803/42706258-c113b514-869b-11e8-9062-f51a3fc98299.png)
3 ![screen shot 2018-07-13 at 12 52 45 pm](https://user-images.githubusercontent.com/1492803/42706259-c121660a-869b-11e8-8fbb-8688eac4d2e4.png)
2 ![screen shot 2018-07-13 at 12 52 32 pm](https://user-images.githubusercontent.com/1492803/42706260-c12ffb8e-869b-11e8-8c32-7084379dd23c.png)
1 ![screen shot 2018-07-13 at 12 50 59 pm](https://user-images.githubusercontent.com/1492803/42706261-c13ee522-869b-11e8-840d-096b74770baa.png)
Tropical * ![screen shot 2018-07-13 at 12 50 29 pm](https://user-images.githubusercontent.com/1492803/42706262-c14fb9ce-869b-11e8-80db-3f7562fdbfd0.png)

**Comment by dblodgett-usgs** [comment]
So -- should I change the dot size AND color?!?

**Comment by aappling-usgs** [comment]
Nah, just know that you have both at your disposal. Do something that looks nice. And has a color scheme that's compatible with the rest of the figure...those colors up above are really bright...
