### ISSUE TITLE
Bug in simplification of river geometry.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/vizstorm-GIF#73]
This ain't right.
![screen shot 2018-07-13 at 10 21 28 am](https://user-images.githubusercontent.com/1492803/42699505-962fa066-8686-11e8-8146-e0a30243b127.png)

**Comment by aappling-usgs** [comment]
yikes!

**Comment by dblodgett-usgs** [comment]
It appears that this is an artifact of total drainage area including diverted paths. The downstream ends of the flowlines that shouldn't be included are on little diverted paths that are part of the main stem. The totdasqkm reflects the total upstream area but the divdasqkm does not. I'll switch my filter to divdasqm (divergence routed drainage area) and cross my fingers.

**Comment by dblodgett-usgs** [comment]
![screen shot 2018-07-13 at 11 06 21 am](https://user-images.githubusercontent.com/1492803/42701680-d741f814-868c-11e8-8f3c-7559647d3ddc.png)
ahhh that's better.
