### ISSUE TITLE
graphical datetime 

### ISSUE THREAD

**Issue by jzwart** [USGS-VIZLAB/vizstorm-GIF#79]
splitting off from #30 

Nice to have: One creative turn to consider might be to make this info graphical in some way - could be a calendar with date squares filling in over time, for example. Something to help people see where they are in time, and connect it to where they were in their own lives at each time point, without having to read and think about a text-based date-time stamp.

**Comment by aappling-usgs** [comment]
I still sorta like the calendar idea, but going a little simpler, what about an x axis with date labels under the sparklines? Could optionally have a little arrow pointing to where you are in each frame.

![image](https://user-images.githubusercontent.com/12039957/44540521-0fe96900-a6d5-11e8-8716-70962a46b2be.png)

**Comment by jzwart** [comment]
Ooo yeah I like that. This would go under _all_ the sparklines not _each_ sparkline, right?

**Comment by aappling-usgs** [comment]
Yeah, just one for all the lines together

**Comment by lindsayplatt** [comment]
We do this now! Thanks to #220

![image](https://user-images.githubusercontent.com/13220910/133823266-de3f8253-463d-41f3-8358-08ab9b9f28ed.png)
