### ISSUE TITLE
try storm with a different image size (for presentation)

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizstorm-GIF#92]
We would like to use this vizstorm gif in the HDAC vizzies presentation. It would be great if it could be a square (so the Instagram aspect ratio) because we could fit the gif and some text onto a wide format slide. This will obviously take some rejiggering of the components that make up the viz.

- [ ] resize the gif to be a square
- [ ] ignore gages that have gaps (there still appears to be a funky one, 7th from bottom)
- [ ] slow the gif down and actually march through the entire time period

Here's the gif created from the most recent PR (#91):

![vizstorm](https://user-images.githubusercontent.com/13220910/43923068-50506704-9be6-11e8-873a-432d88165571.gif)

**Comment by jread-usgs** [comment]
I can probably take this on w/ #82 since they are similar.

**Comment by jread-usgs** [comment]
![gif_frame_a_20170902_00](https://user-images.githubusercontent.com/2349007/44343481-a4dd2f80-a453-11e8-8132-21b507f6d7e3.png)

@lindsaycarr let me know if you would like to use this storm. I can generate the gif and code is [here](https://github.com/jread-usgs/vizstorm-GIF/tree/Harvey-al092017)

**Comment by lindsaycarr** [comment]
@jread-usgs yes, I think that would work nicely!
