### ISSUE TITLE
Move streamflow data fetch from visualize to fetch?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizstorm-GIF#99]
Not sure why this happens in `6_` instead of `1_`, but if we move it to `1_`, we can get rid of sites that don't have data during the period of interest, instead of carrying them all the way along to the visualization step.

**Comment by jread-usgs** [comment]
This seems like a fairly big overhaul to change, but the issue right now is we don't know if a site has data for the period of interest until we download it, and we don't do that until we are prepping the plotting function `prep_spark_funs_data()`

**Comment by jread-usgs** [comment]
Not sure why this
```r
warning(sprintf('no stage data for dateTime<=%s and site=%s', DateTime, site))
      shapes[[site]] <- NULL
      next
``` 
was commented out and replaced w/ a `stop()`

**Comment by aappling-usgs** [comment]
Streamflow data fetch does happen in 1_fetch/src/fetch_streamdata.R and is called in 1_fetch.yml line 112.

**Comment by aappling-usgs** [comment]
If we change the stop() back to a warning() we probably need to add/change some logic in prep_gage2spark_fun() to accommodate an unreliable number of sparklines

**Comment by jread-usgs** [comment]
I think this issue was created because of my confusion as to where these things are happening. The fetch isn't happening in `6_`, it just seemed that way to me in some of the builds based on the order of target builds.
